sonar.projectKey=MaximEichenberger04_sopra-fs26-group-27-client
sonar.organization=maximeichenberger04

sonar.projectName=sopra-fs26-group-27-client
sonar.projectVersion=1.0

sonar.sources=app,public
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/out/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.sourceEncoding=UTF-8
