sonar.projectKey=MaximEichenberger04_sopra-fs26-group-27-client
sonar.organization=maximeichenberger04

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=.